version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://103.18.20.205:8070
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production 
      - JWT_SECRET=your_jwt_secret_key_here # Change this in production
      - AUTH_TOKEN_EXPIRY=86400 # 24 hours in seconds 